@echo off
echo Iniciando setup automático con venv...

:: 1. Crear entorno virtual
python -m venv venv

:: 2. Activar entorno
call venv\Scripts\activate

:: 3. Instalar dependencias
python -m pip install --upgrade pip
pip install -r config\requirements.txt

:: 4. Ejecutar aplicación
echo Ejecutando aplicación...
python src\main.py
